version: '3.7'

services:
    web1: 
        build: ./test_app1
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
          - ./test_app1/:/usr/src/app/
        env_file:
          - ./test_app1/.env.dev
        depends_on:
        - db1
        networks:
        - localnet1
    db1:
        image: postgres:12.0-alpine
        volumes:
          - postgres_data1:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=simple_django
          - POSTGRES_PASSWORD=simple_django
          - POSTGRES_DB=simple_django1_dev
        ports:
         - 6432:5432
        networks:
        - localnet1
    web2: 
        build: ./test_app2
        command: python3 manage.py runserver 0.0.0.0:8001
        volumes:
          - ./test_app2/:/usr/src/app/
        env_file:
          - ./test_app2/.env.dev
        depends_on:
        - db2
        networks:
        - localnet2
    db2:
        image: postgres:12.0-alpine
        volumes:
          - postgres_data2:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=simple_django
          - POSTGRES_PASSWORD=simple_django
          - POSTGRES_DB=simple_django_dev
        ports:
        - 7432:5432        
        networks:
        - localnet2
    nginx:
        build: ./nginx
        ports:
         - 80:80
        depends_on:
         - web1
         - web2
        networks:
         - localnet1
         - localnet2
volumes:
    postgres_data1:
    postgres_data2:

networks:
    localnet1:
        driver: bridge
    localnet2:
        driver: bridge
